# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('sname', models.CharField(max_length=26)),
                ('smarks', models.IntegerField()),
            ],
        ),
    ]
